"""
Django settings for weatherapp project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import dj_database_url
from pathlib import Path
from decouple import config
import os
import sys
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("DJANGO_SECRET_KEY",
                    default="django-insecure-fallback-development-key")
API_KEY = config("API_KEY")
API_URL = config("API_URL")
FORECAST_URL = config("FORECAST_URL")
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", default=False, cast=bool)


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "storages",
    "posts",      # <-- Clear name
    "users",      # <-- Clear name
    "weather",
    
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "weatherapp.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "weatherapp.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================
# 1. Start with a local SQLite database configuration by default
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
        ssl_require=True
    )
}
# Overwrite with explicit Supabase production details if running on Render
if os.environ.get('DATABASE_URL'):
    DATABASES['default'].update({
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT'),
        'NAME': config('DB_NAME'),
    }) 
        
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage',
    AWS_ACCESS_KEY_ID = config('SUPABASE_S3_ACCESS_KEY')
    AWS_SECRET_ACCESS_KEY = config('SUPABASE_S3_SECRET_KEY')
    AWS_STORAGE_BUCKET_NAME = config('SUPABASE_S3_BUCKET')
    AWS_S3_ENDPOINT_URL = config('SUPABASE_S3_ENDPOINT')
    AWS_S3_REGION_NAME = config('SUPABASE_S3_REGION')
    AWS_S3_ADDRESSING_STYLE = 'path'
    AWS_DEFAULT_ACL = 'public-read'
    AWS_QUERYSTRING_AUTH = False
        
    
# 2. Overwrite with PostgreSQL ONLY if DATABASE_URL exists (like on Render)
# if os.environ.get("DATABASE_URL"):
# import dj_database_url
# DATABASES["default"] = dj_database_url.config(
#  conn_max_age=600, ssl_require=True)


# ==============================================================================
# SECURITY & ENVIRONMENT OVERRIDES
# ==============================================================================
# If running locally, make sure DEBUG is True so you can build and test safely
if not os.environ.get("DATABASE_URL"):
    DEBUG = False
else:
    DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".vercel.app",
    
]

# ==============================================================================
# STATIC FILES CONFIGURATION
# ==============================================================================
STATIC_URL = "/static/"
MEDIA_URL = "/media/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_ROOT = BASE_DIR / "media"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Tell WhiteNoise to compress static assets
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
